# Generated by Django 4.2 on 2023-04-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_add_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee', serialize=False, to='accounts.customer')),
                ('join_date', models.DateField(auto_now=True)),
                ('job_title', models.CharField(default='employee', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyDirector',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.employee')),
            ],
            bases=('accounts.employee',),
        ),
        migrations.CreateModel(
            name='MyManager',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.employee')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='managers', to='accounts.mydirector')),
            ],
            bases=('accounts.employee',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='drivers', to='accounts.mymanager')),
            ],
            bases=('accounts.employee',),
        ),
    ]
