# Generated by Django 4.2.2 on 2023-07-10 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=256)),
                ("report_datetime", models.DateTimeField(auto_now_add=True)),
                ("answer", models.TextField(blank=True, default="", max_length=256)),
                ("complete_datetime", models.DateTimeField(null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "manager"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("answer_report", "Can answer to any reports of others")
                ],
            },
        ),
    ]
