# Generated by Django 4.2.2 on 2023-07-10 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=12, unique=True)),
                ("brand", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=32)),
                (
                    "type",
                    models.CharField(
                        choices=[("B", "Basic"), ("V", "Van"), ("OR", "Off-Road")],
                        max_length=5,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1980, 1980),
                            (1981, 1981),
                            (1982, 1982),
                            (1983, 1983),
                            (1984, 1984),
                            (1985, 1985),
                            (1986, 1986),
                            (1987, 1987),
                            (1988, 1988),
                            (1989, 1989),
                            (1990, 1990),
                            (1991, 1991),
                            (1992, 1992),
                            (1993, 1993),
                            (1994, 1994),
                            (1995, 1995),
                            (1996, 1996),
                            (1997, 1997),
                            (1998, 1998),
                            (1999, 1999),
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                        ]
                    ),
                ),
                (
                    "_class",
                    models.CharField(
                        choices=[("B", "Basic"), ("U", "Upper"), ("L", "Luxury")],
                        max_length=5,
                        verbose_name="class",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("R", "Red"),
                            ("OR", "Orange"),
                            ("YL", "Yellow"),
                            ("GRE", "Green"),
                            ("BLU", "Blue"),
                            ("VL", "Violet"),
                            ("BLA", "Black"),
                            ("GRY", "Gray"),
                            ("WH", "White"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
