# Generated by Django 4.2.2 on 2023-07-10 11:45

import commons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.CharField(max_length=300)),
                ("end", models.CharField(max_length=300)),
                ("price", commons.models.MoneyField(decimal_places=2, max_digits=10)),
                ("note", models.TextField(blank=True, max_length=128)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "car_type",
                    models.CharField(
                        choices=[("B", "Basic"), ("V", "Van"), ("OR", "Off-Road")],
                        default="B",
                        max_length=5,
                    ),
                ),
                (
                    "car_class",
                    models.CharField(
                        choices=[("B", "Basic"), ("U", "Upper"), ("L", "Luxury")],
                        default="B",
                        max_length=5,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("accept_order", "Can accept any open orders of others")
                ],
            },
        ),
    ]
